name: MiniDLNA

on:
  push:
    paths:
    - 'minidlna/**'
    - '.github/workflows/minidlna.yml'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: meibensteiner
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: minidlna/Dockerfile
          push: true
          tags: ghcr.io/meibensteiner/minidlna:latest
          platforms: linux/amd64,linux/arm64
